### ISSUE TITLE
[Bug]: UI breaks for some blocks on explorer.shimmer.network/shimmer/block/<blockId>

### ISSUE THREAD

**Issue by servrox** [iotaledger/explorer#814]
### Issue description

If I enter a blockId in the search field, it correctly recognizes that it is a block; but then a blank page is displayed at https://explorer.shimmer.network/shimmer/block/<blockId>

For example when searching for https://explorer.shimmer.network/shimmer/search/0xd3b004298e8a3366c05e27272113bb096fe5ca9677eebf1042b6a92a9515f143 a blank page is shown -> https://explorer.shimmer.network/shimmer/block/0xfff12a86b1bba817b7640633186879648fe4aa931a810646360f857c023c20a6

The behavior doesnt seem to be a general problem, since the page can be displayed for e.g. https://explorer.shimmer.network/shimmer/block/0x2549725dd428cbfcee964c4535a4c51b342b2e19a238a179701e164c08c8d1bb.

There's an error logged to the web console:
`TypeError: Cannot read properties of undefined (reading 'replace')` 
which probably because `undefined` is passed to https://github.com/iotaledger/explorer/blob/dev/api/src/utils/hexHelper.ts#L49

### Expected behaviour

Display **block information** page or the **not found** page.

### Actual behaviour

Blank page is displayed.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Go to https://explorer.shimmer.network/shimmer
2. Insert `0xfff12a86b1bba817b7640633186879648fe4aa931a810646360f857c023c20a6` in the search
3. Hit enter
4. Cry

### Errors

```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Function.value (main.14a945ca.js:2:2181965)
    at Function.value (main.14a945ca.js:2:2183619)
    at main.14a945ca.js:2:2193653
    at iu (main.14a945ca.js:2:1472018)
    at Tl (main.14a945ca.js:2:1492245)
    at main.14a945ca.js:2:1488835
    at E (main.14a945ca.js:2:1575587)
    at MessagePort.M (main.14a945ca.js:2:1576121)
```

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by servrox** [comment]
Ok just figured out that it has to do with whether there is a `tag` in the `payload` or not.

`"payload": { "type":5, "tag": "0x68656c6c6f20776f726c64", "data":"0x73657276726F7820736F6C7574696F6E7320676F65732053505943452E350A2331333337" }` works ✅
https://explorer.shimmer.network/shimmer/block/0x3da0257cbcb6e7a0c5485175bcd76a0aff521cd37fd8bf2e447535a56ac90034

`"payload": { "type":5, "data":"0x73657276726F7820736F6C7574696F6E7320676F65732053505943452E350A2331333337" }}` works not ❌
https://explorer.shimmer.network/shimmer/block/0x02c194041c1b0e055d6cf032b94a6a2e5a4fc56172ae910cfc3cf929c2c31fd9

**Comment by servrox** [comment]
Fixed with https://github.com/iotaledger/explorer/commit/e6d6b94f38595ce495b40cad7d24994ca91dd28a
